[package]
name = "tempeh-window"
version = "0.1.0"
authors = ["Andra Antariksa <andra.antariksa@gmail.com>"]
edition = "2018"

[dependencies]
raw-window-handle = "0.4.3"
tempeh-math = { version = "0.1.0", path = "../tempeh-math" }
tempeh-engine = { version = "0.1.0", path = "../tempeh-engine" }
