name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ubuntu_x11:
    name: Build Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: humbletim/setup-vulkan-sdk@v1.0.3
      - uses: lukka/get-cmake@latest
      - name: Setup
        run: |
          sudo apt install gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update

          sudo apt install mesa-common-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libx11-dev mono-devel libxrandr-dev libxcb-xkb-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libcurl4-openssl-dev -y

          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$(pwd)/depot_tools:$PATH
          cd external/dawn
          cp scripts/standalone.gclient .gclient
          gclient sync
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            build/
          key: ${{ runner.os }}-master
      - name: Build
        run: |
          export MONO_PROJECT=/usr/include/mono-2.0/

          mkdir build
          cd build
          cmake .. -DTEMPEH_ENABLE_TEST=ON
          cmake --build .
      - name: Run test
        run: |
          ./build/test/tempeh_core_test
  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: humbletim/setup-vulkan-sdk@v1.0.3
      - uses: lukka/get-cmake@latest
      - name: Setup
        run: |
          Invoke-WebRequest -Uri https://download.mono-project.com/archive/6.12.0/windows-installer/mono-6.12.0.107-x64-0.msi -OutFile mono.msi
          Start-Process -Verb RunAs msiexec.exe -Wait -ArgumentList '/I mono.msi /quiet'

          $env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          $env:Path += ";$pwd\depot_tools"
          cd external\dawn
          copy scripts\standalone.gclient .gclient
          gclient sync
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            build/
          key: ${{ runner.os }}-master
      - name: Build
        run: |
          $env:MONO_INCLUDE_DIR = "C:\Program Files\Mono\include\mono-2.0\"

          mkdir build
          cd build
          cmake .. -DTEMPEH_ENABLE_TEST=ON -G "Ninja"
          cmake --build .
      - name: Run test
        run: |
          .\build\test\tempeh_core_test.exe
