name: Rust

on:
  push:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] #, windows-latest, macOS-latest ]
    steps:
      - name: Ubuntu preprocessing
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libxcb-xfixes0-dev libxcb-shape0-dev
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo test --all --verbose
      - name: Build
        run: cargo build --verbose
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
